In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
A = [[1, 2, 3], [4, 5, 6]]
print(A)
print()
A = np.array(A)
print(A, '\n')

#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
B = np.array(A, dtype = float)
print(B)
B = np.array(B, dtype = complex)
print(B, '\n')

C = np.array(A, ndmin = 3)  #declaring C as a 3-D matrix
print(C)

[[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]] 

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]] 

[[[1 2 3]
  [4 5 6]]]


'C is declared a 3D matrix'

In [24]:
print(A.shape)  #(rows, columns) = (2, 3)
print(C.shape)  #(xx, rows, columns) = (1, 2, 3)

A.shape = (3, 2)
print(A)

D = A.reshape(1, 6)
print(D)

print('\n')
a = np.arange(36)
print(a)
print(a.ndim)
a = a.reshape(3, 4, 3)
print(a)
print(a.ndim)
a = a.reshape(2, 3, 3, 2)
print(a)
print(a.ndim)

(3, 2)
(1, 2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
3
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]

  [[12 13]
   [14 15]
   [16 17]]]


 [[[18 19]
   [20 21]
   [22 23]]

  [[24 25]
   [26 27]
   [28 29]]

  [[30 31]
   [32 33]
   [34 35]]]]
4


In [45]:
#numpy.empty(shape, dtype = float, order = 'C')
D = np.empty([3, 4], dtype = int)  #random, uninitialized values
print(D)

#numpy.zeros(shape, dtype = float, order = 'C')
#numpy.ones(shape, dtype = None, order = 'C')
D = np.zeros((3, 2), dtype = float)  #replace zeros by ones for ones
print(D)


#numpy.asarray(a, dtype = None, order = None)
#converting lists and tuples into arrays
x = [(1,2,3),(4,5)]   #rare case
D = np.asarray(x) 
print(D)
print(D.ndim)
print(D.shape)


#numpy.arange(start, stop, step, dtype)
E = np.arange(18, 54, 3, dtype = complex)
print(E)

#numpy.linspace(start, stop, num, endpoint, retstep, dtype)
E = np.linspace(30, 50)
print(E)
print(E.shape)

E = np.linspace(30, 50, 6)  #division into 6-1=5 intervals, checkpoints needed = 6
print(E)

E = np.linspace(30, 50, 6, dtype = int)
print(E)

E = np.linspace(30, 50, 6, endpoint = False)   #dtype should not be int.  here, checkpoints = 6 fixed, but intervals = 6 also.
print(E)

E = np.linspace(30, 50, 6, endpoint = False, retstep = True)   #return stepsize
print(E)


#numpy.logspace(start, stop, num, endpoint, base, dtype)
#similar to linspace, but on a logarithmic scale

[[          0  1077805056 -1431655765  1077979818]
 [ 1431655765  1078089045           0  1078198272]
 [-1431655765  1078307498  1431655766  1078416725]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[(1, 2, 3) (4, 5)]
1
(2,)
[18.+0.j 21.+0.j 24.+0.j 27.+0.j 30.+0.j 33.+0.j 36.+0.j 39.+0.j 42.+0.j
 45.+0.j 48.+0.j 51.+0.j]
[30.         30.40816327 30.81632653 31.2244898  31.63265306 32.04081633
 32.44897959 32.85714286 33.26530612 33.67346939 34.08163265 34.48979592
 34.89795918 35.30612245 35.71428571 36.12244898 36.53061224 36.93877551
 37.34693878 37.75510204 38.16326531 38.57142857 38.97959184 39.3877551
 39.79591837 40.20408163 40.6122449  41.02040816 41.42857143 41.83673469
 42.24489796 42.65306122 43.06122449 43.46938776 43.87755102 44.28571429
 44.69387755 45.10204082 45.51020408 45.91836735 46.32653061 46.73469388
 47.14285714 47.55102041 47.95918367 48.36734694 48.7755102  49.18367347
 49.59183673 50.        ]
(50,)
[30. 34. 38. 42. 46. 50.]
[30 34 38 42 46 50]
[30.         33.33333333 36.6666

In [68]:
#Indexing & Slicing

a = np.arange(10)
print(a)

print(a[5])
print(a[1:5])
print(a[3:])
print(a[4:9:2])
print(a[2:8:3])

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1:3])  #2nd & 3rd rows
print(a[..., 1])  #2nd column
print(a[2, ...])  #3rd row
print(a[..., 1:])  #all columns starting from 2nd

print()
#Advanced Indexing
#Integer Indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]  #(0, 0), (1, 1), (2, 0) co-ordinates are chosen
print(y)

x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
rows = np.array([[0, 0], [3, 3]])
columns = np.array([[0, 2], [0, 2]])
y = x[rows, columns]  #choosing corner elements of the matrix
print(y)

z = x[1:4, 1:3]  #slicing
print(z)
z = x[1:4, [1, 2]]  #using advanced indexing for columns
print(z)

#Boolean Indexing
print(x[x>5])  #all items in x greater than 5


#Broadcasting  #capability of NumPy to operate two matrices of different dimensions via broadcasting

print(z+z)  #no broadcasting

x1 = np.array([3, 4, 5])
x2 = np.array([[0, 1, 2], [3, 4, 5]])
print(x+x1)  #(4, 3)  & (1, 3) broadcasting done

#print(x+x2)....broadcasting not possible

[0 1 2 3 4 5 6 7 8 9]
5
[1 2 3 4]
[3 4 5 6 7 8 9]
[4 6 8]
[2 5]
[[4 5 6]
 [7 8 9]]
[2 5 8]
[7 8 9]
[[2 3]
 [5 6]
 [8 9]]

[1 4 5]
[[ 0  2]
 [ 9 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]
[ 6  7  8  9 10 11]
[[ 8 10]
 [14 16]
 [20 22]]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]
 [12 14 16]]


In [86]:
#Iterating Over The Array
A = np.arange(0, 100, 5)
A = A.reshape(4, 5)

print('A:', A)

B = A.T
print('B:', B)

for i in np.nditer(A):  #The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering.
    print(i, end = ' ')
print()

for i in np.nditer(B):
    print(i, end = ' ')
print()

for i in np.nditer(A, order = 'F'):  #If the same elements are stored using F-style order, the iterator chooses the more efficient way of iterating over an array.
    print(i, end = ' ')
print()

for i in np.nditer(A, order = 'C'):
    print(i, end = ' ')
print()

for i in np.nditer(B, order = 'F'):
    print(i, end = ' ')
print()

for i in np.nditer(B, order = 'C'):
    print(i, end = ' ')
print()

A: [[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
B: [[ 0 25 50 75]
 [ 5 30 55 80]
 [10 35 60 85]
 [15 40 65 90]
 [20 45 70 95]]
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 
0 25 50 75 5 30 55 80 10 35 60 85 15 40 65 90 20 45 70 95 
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 
0 25 50 75 5 30 55 80 10 35 60 85 15 40 65 90 20 45 70 95 


In [108]:
#Array Manipulation
#numpy.reshape(arr, newshape, order')

#Transpose
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(a)
b = a.T
print(b)
c = a.transpose()
print(c)
d = np.transpose(a)
print(d[2][1])  #printing elements of a numpy array

#Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a+b)  #no concatenation

#numpy.concatenate((a1, a2, ...), axis)
c = np.concatenate((a, b))  #default axis=0
print(c)
c = np.concatenate((a, b), axis=1)
print(c)

c = np.hstack((a, b))  #horizontal stacking
print(c)

c = np.vstack((a, b))  #vertical stacking
print(c)

#Array Splitting
#numpy.split(ary, indices_or_sections, axis)

a = np.arange(9)
b = np.split(a, 3)  #splits into 3 equal parts
print(b)
c = np.split(a, [4, 7])  #splits at indices 4 &7
print(c)

a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
b = np.hsplit(a, 2)
print(b)
c = np.vsplit(a, 2)
print(c)

#Adding or Removing Elements


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
6
[[ 6  8]
 [10 12]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [ ]:
#String Functions
